php_error_insight:
    enabled: true
    backend: 'none'  # Change to 'local', 'openai', 'anthropic', 'google' as needed
    language: 'en'
    output: 'auto'
    verbose: false

    # Uncomment and configure for specific backends:
    # model: 'llama3:instruct'     # For local/ollama backend
    # api_url: 'http://localhost:11434'  # For local backend
    # api_key: '%env(PHP_ERROR_INSIGHT_API_KEY)%'  # For external APIs
    # template: 'custom/error.html.twig'  # Custom error template